config/routes.rb
Rails.application.routes.draw do
  root to: "homes#top"
  get '/home/about', to: 'homes#about'
  devise_for :users, controllers: { registrations: 'registrations' }
  resources :books, only: [:index, :show, :create, :edit, :update, :destroy]
  resources :users, only: [:index, :show, :edit, :update]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  has_one_attached :image
  belongs_to :user
  
  validates :title, presence: true
  validates :body, presence: true, length: { maximum: 200 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  validates :name, uniqueness: true, length: { in: 2..20 }
  validates :introduction, length: { maximum: 50 }
  
  has_many :books, dependent: :destroy
  
  has_one_attached :profile_image
  
  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/default-image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!, except: [:top, :about]
  before_action :configure_permitted_parameters, if: :devise_controller?
  
  def after_sign_in_path_for(resource)
    user_path(resource)
  end
  
  protected
  
  def configure_permitted_parameters
    added_attrs = [:user_name, :email, :password, :password_confirmation, :remember_me]
    devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
    devise_parameter_sanitizer.permit :account_update, keys: added_attrs
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      flash[:notice] = "You have created book successfully."
      redirect_to book_path(@book.id)
    else
      @booknew = Book.new(book_params)
      @books = Book.all
      render :index
    end
  end

  def index
    @booknew = Book.new
    @book = Book.new
    @books = Book.all
  end

  def show
    @booknew = Book.new
    @book = Book.find(params[:id])
    @books = Book.all
    @user = User.find(@book.user_id)
  end
  
  def edit
    is_matching_login_user
    @book = Book.find(params[:id])
  end
  
  def update
    is_matching_login_user
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:notice] = "You have updated book successfully."
      redirect_to book_path(@book)
    else
      render :edit
    end
  end
  
  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to '/books'
  end
  
private

  def book_params
    params.require(:book).permit(:title, :body)
  end
  
  def is_matching_login_user
    book = Book.find(params[:id])
    user = book.user
    unless user == current_user
      redirect_to books_path
    end
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
  
  def about
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  def create
    super do |resource|
      if resource.persisted?
        flash[:notice] = "ユーザーの新規登録が完了しました"
      end
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @booknew = Book.new
    @users = User.all
  end
  
  def show
    @booknew = Book.new
    @user = User.find(params[:id])
    @books = @user.books
  end

  def edit
    is_matching_login_user
    @user = User.find(params[:id])
  end
  
  def update
    is_matching_login_user
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "You have updated user successfully."
      redirect_to user_path(@user.id)
    else
      render :edit
    end
  end
  
private
  
  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end
  
  def is_matching_login_user
    user = User.find(params[:id])
    unless user.id == current_user.id
      redirect_to user_path(current_user.id)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_new.html.erb
<style>
.expanded-width {
  width: 100%;
  box-sizing: border-box;
  margin-bottom: 10px;
}
</style>
<div class="col-md-3">
      <h2>User info</h2>
      <% if @user.present? %>
        <%= image_tag @user.get_profile_image(100,100) %>
        <table class="table">
          <tbody>
            <tr>
              <th>name</th>
              <th><%= @user.name %></th>
            </tr>
            <tr>
              <th>introduction</th>
              <th><%= @user.introduction %></th>
            </tr>
          </tbody>
        </table>
        <div class="row">
          <a class="btn btn-outline-secondary btn-block" href="/users/<%= @user.id %>/edit">
            <i class="fa-solid fa-user-gear"></i>
          </a>
        </div>
      <% else %>
        <%= image_tag current_user.get_profile_image(100,100) %>
        <table class="table">
          <tbody>
            <tr>
              <th>name</th>
              <th><%= current_user.name %></th>
            </tr>
            <tr>
              <th>introduction</th>
              <th><%= current_user.introduction %></th>
            </tr>
         </tbody>
        </table>
        <div class="row">
          <a class="btn btn-outline-secondary btn-block" href="/users/<%= current_user.id %>/edit">
            <i class="fa-solid fa-user-gear"></i>
          </a>
        </div>
      <% end %>
      <h2 class="mt-3">New book</h2>
      <%= form_with model: book do |f| %>
        <label>Title</label>
        <%= f.text_field :title, class: "expanded-width" %>
        <label>Opinion</label>
        <%= f.text_area :body, class: "expanded-width" %>
        <input type="submit" name="commit" value="Create Book" class="btn btn-success" data-disable-with="Create Book">
      <% end %>
    </div>

app/views/books/edit.html.erb
<style>
.expanded-width {
  width: 100%;
  box-sizing: border-box;
}
.input{
  margin-bottom: 10px;
}
</style>
<p id="notice"></p>
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h1>Editing Book</h1>
      <div id="error_explanation">
        <% if @book.errors.any? %>
        <h3><%= @book.errors.count %> error prohibited this obj from being saved:</h3>
        <ul>
          <% @book.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
        <% end %>
      </div>
      <%= form_with model: @book do |f| %>
        <div class="input">
          <label>Title</label>
          <%= f.text_field :title, class: "expanded-width" %>
        </div>
        <div class="input">
          <label>Opinion</label>
          <%= f.text_area :body, class: "expanded-width" %>
        </div>
        <div class="input">
          <input type="submit" name="commit" value="Update Book" class="btn btn-success" data-disable-with="Update Book">
        </div>
          
        <%= link_to "Show", book_path(@book.id) %>
        |
        <%= link_to "Back", '/books' %>
        
      <% end %>
    </div>
  </div>
</div>

app/views/books/index.html.erb
<p id="notice"></p>
<div class="container px-5 px-sm-0">
  <div id="error_explanation">
    <% if @book.errors.any? %>
    <h3><%= @book.errors.count %> error prohibited this obj from being saved:</h3>
    <ul>
      <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
    <% end %>
  </div>
  <div class="row">
    <%= render 'new', book: @booknew %>
    <div class="col-md-8 offset-md-1">
      <h2>Books</h2>
      <table class="table">
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
          </tr>
        </thead>
        <tbody>
          <% @books.each do |book| %>
            <tr>
              <td><a href="/users/<%= book.user_id %>"><%= image_tag 'default-image', size: "80x80" %></a></td>
              <td><a href="/books/<%= book.id %>"><%= book.title %></a></td>
              <td><%= book.body %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/books/show.html.erb
<div>
  <%= flash[:notice] %>
</div>
<p id="notice"></p>
<div class="container px-5 px-sm-0">
  <div class="row">
    <%= render 'new', book: @booknew %>
    <div class="col-md-8 offset-md-1">
      <h2>Book detail</h2>
      <table class="table">
        <tbody>
            <tr>
              <td>
                <a href="/users/<%= @book.user_id %>">
                  <%= image_tag 'default-image', size: "100x100" %><br>
                  <%= @user.name %>
                </a>
              </td>
              <td><a href="/books/<%= @book.id %>"><%= @book.title %></a></td>
              <td><%= @book.body %></td>
              <% if @book.user_id == current_user.id %>
                <td><a class="btn btn-sm btn-success" href="/books/<%= @book.id %>/edit">Edit</a></td>
                <td><a class="btn btn-sm btn-danger" rel="nofollow" data-method="delete" href="/books/<%= @book.id %>">Destroy</a></td>
              <% end %>
            </tr>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/homes/about.html.erb
<p id="notice"></p>
<div class="container">
  <div class="row">
    <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
      <h1>Welcome to <i class="fa-solid fa-book"></i><strong>Bookers</strong>  !</h1>
    </div>
  </div>
</div>

app/views/homes/top.html.erb
<div>
  <%= flash[:notice] %>
</div>
<p id="notice"></p>
<div class="container">
  <div class="row">
    <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
      <h1>welcome to <i class="fa-solid fa-book"></i><strong>Bookers</strong>  !!</h1>
      <p>In  <i class="fa-solid fa-book"></i><strong>Bookers</strong>, </p>
      <p>you can share and exchange  your opinions , inpressions , and emotions</p>
      <p> about various books!</p>
      <div class="btn-wrapper col-10 mx-auto">
        <div class="row">
          <a class="btn btn-info btn-sm btn-block mb-3 sign_in" href="/users/sign_in">Log in</a>
        </div>
        <div class="row">
          <a class="btn btn-success btn-sm btn-block sign_up" href="/users/sign_up">Sign up</a>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://kit.fontawesome.com/2911f289b2.js" crossorigin="anonymous"></script>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
      <a class="navbar-brand" href="/"><span>Bookers</span></a>
      <button class="navbar-toggler collapsed" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="navbar-collapse collapse" id="navbarNavDropdown" style="">
        <ul class="navbar-nav ml-auto">
          <% if user_signed_in? %>
            <li>
              <a href="/users/<%= current_user.id %>"  class="nav-link text-light">
                <i class="fa-solid fa-house"></i>
                Home
              </a>
            </li>
            
            <li>
              <a href="<%= users_path %>" class="nav-link text-light">
                <i class="fa-solid fa-users"></i>
                Users
              </a>
            </li>
            
            <li>
              <a href="<%= books_path %>" class="nav-link text-light">
                <i class="fa-solid fa-book-open"></i>
                Books
              </a>
            </li>
            
            <li class="nav-item">
              <%= link_to destroy_user_session_path, method: :delete, class: 'nav-link text-light' do %>
                <i class="fa-solid fa-right-from-bracket"></i>
                Log out
              <% end %>
            </li>
            
          <% else %>
            <li>
              <a href="<%= root_path %>" class="nav-link text-light">
                <i class="fa-solid fa-house"></i>
                Home
              </a>
            </li>
            
            <li>
              <a href="<%= home_about_path %>" class="nav-link text-light">
                <i class="fa-solid fa-link"></i>
                About
              </a>
            </li>
            
            <li>
              <a href="<%= new_user_registration_path %>" class="nav-link text-light">
                <i class="fa-solid fa-user-plus"></i>
                Sign up
              </a>
            </li>
              
            <li>
              <a href="<%= new_user_session_path %>" class="nav-link text-light">
                <i class="fa-solid fa-right-to-bracket"></i>
                Log in
              </a>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
    </header>
    <%= yield %>
    <footer>
      <div class="container mt-5">
        <div class="row">
          <div class="mx-auto">
            <p>CopyRight Infratop.inc</p>
          </div>
        </div>
      </div>
    </footer>
  </body>
</html>

app/views/users/_new.html.erb
<style>
.expanded-width {
  width: 100%;
  box-sizing: border-box;
  margin-bottom: 10px;
}
</style>
<div class="col-md-3">
      <h2>User info</h2>
      <% if @user.present? %>
        <%= image_tag @user.get_profile_image(100,100) %>
        <table class="table">
          <tbody>
            <tr>
              <th>name</th>
              <th><%= @user.name %></th>
            </tr>
            <tr>
              <th>introduction</th>
              <th><%= @user.introduction %></th>
            </tr>
          </tbody>
        </table>
        <div class="row">
          <a class="btn btn-outline-secondary btn-block" href="/users/<%= @user.id %>/edit">
            <i class="fa-solid fa-user-gear"></i>
          </a>
        </div>
      <% else %>
        <%= image_tag current_user.get_profile_image(100,100) %>
        <table class="table">
          <tbody>
            <tr>
              <th>name</th>
              <th><%= current_user.name %></th>
            </tr>
            <tr>
              <th>introduction</th>
              <th><%= current_user.introduction %></th>
            </tr>
         </tbody>
        </table>
        <div class="row">
          <a class="btn btn-outline-secondary btn-block" href="/users/<%= current_user.id %>/edit">
            <i class="fa-solid fa-user-gear"></i>
          </a>
        </div>
      <% end %>
      <h2 class="mt-3">New book</h2>
      <%= form_with model: book do |f| %>
        <label>Title</label>
        <%= f.text_field :title, class: "expanded-width" %>
        <label>Opinion</label>
        <%= f.text_area :body, class: "expanded-width" %>
        <input type="submit" name="commit" value="Create Book" class="btn btn-success" data-disable-with="Create Book">
      <% end %>
    </div>

app/views/users/edit.html.erb
<style>
.expanded-width {
  width: 100%;
  box-sizing: border-box;
}
.input{
  margin-bottom: 10px;
}
</style>
<p id="notice"></p>
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h2>User info</h2>
      <div id="error_explanation">
        <% if @user.errors.any? %>
        <h3><%= @user.errors.count %> error prohibited this obj from being saved:</h3>
        <ul>
          <% @user.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
        <% end %>
      </div>
      <%= form_with model: @user, authenticity_token: true, multipart: true do |f| %>
        <div class=input>
          <label>Name</label>
          <%= f.text_field :name, class: "expanded-width" %>
        </div>
        <div class=input>
          <label>Image</label>
          <%= f.file_field :profile_image, class: "form-control-file user_image", accept: "image/*" %>
        </div>
        <div class=input>
          <label>introduction</label>
          <%= f.text_area :introduction, class: "expanded-width" %>
        </div>
        <div class=input>
          <input type="submit" name="commit" value="Update User" class="btn btn-secondary" data-disable-with="Update User">
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<p id="notice"></p>
<div class="container px-5 px-sm-0">
  <div class="row">
    <%= render 'new', book: @booknew %>
    <div class="col-md-8 offset-md-1">
      <h2>Users</h2>
      <table class="table">
        <thead>
          <tr>
            <th>image</th>
            <th>name</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <td><%= image_tag user.get_profile_image(80,80) %></td>
              <td><%= user.name %></td>
              <td><a href="/users/<%= user.id %>">Show</a></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div>
  <%= flash[:notice] %>
</div>
<p id="notice"></p>
<div class="container px-5 px-sm-0">
  <div class="row">
    <%= render 'new', book: @booknew %>
    <div class="col-md-8 offset-md-1">
      <h2>Books</h2>
      <table class="table">
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
          </tr>
        </thead>
        <tbody>
          <% @books.each do |book| %>
            <tr>
              <td><a href="/users/<%= book.user_id %>"><%= image_tag @user.get_profile_image(80,80) %></a></td>
              <td><a href="/books/<%= book.id %>"><%= book.title %></a></td>
              <td><%= book.body %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>